version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Toronto
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
