"""Bundle readable Python modules for Noon's single-source browser entry point.

Only imports of our known local modules are removed; no code rewriting, embedded
interpreter, dynamic exec, dependency installation, or custom module loader.
"""
import ast
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SOURCES=[ROOT/'src/model.py',ROOT/'src/uncertainty.py',ROOT/'src/prediction.py',ROOT/'src/visuals.py',
         *sorted((ROOT/'src/lessons').glob('*.py')),ROOT/'src/entry.py']

def bundle():
    sections=['# Generated by tools/build.py. Edit src/, not this file.\n']
    for source in SOURCES:
        text=source.read_text()
        tree=ast.parse(text)
        lines=text.splitlines(keepends=True)
        removed=set()
        for node in tree.body:
            if isinstance(node,ast.ImportFrom) and node.module in {'model','uncertainty','prediction','visuals'}:
                removed.update(range(node.lineno-1,node.end_lineno))
        body=''.join(line for i,line in enumerate(lines) if i not in removed)
        sections.append(f'\n# ---- {source.relative_to(ROOT)} ----\n'+body)
    result=''.join(sections)
    compile(result,'scene.py','exec')
    return result

if __name__=='__main__':
    (ROOT/'scene.py').write_text(bundle())
    print('Built scene.py')
