"""Bundle readable modules for Noon's single-source browser entry point.

Only known local imports are removed. Duplicate top-level definitions are rejected
rather than silently allowing one chapter to overwrite another chapter's names.
There is no runtime loader, dynamic exec, or scene-code rewriting.
"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCAL_MODULES = ('model', 'uncertainty', 'prediction', 'measurement', 'attitude', 'visuals')
SOURCES = [*(ROOT / 'src' / f'{name}.py' for name in LOCAL_MODULES),
           *sorted((ROOT / 'src/lessons').glob('*.py')), ROOT / 'src/entry.py']


def declared_names(node):
    if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
        yield node.name
    elif isinstance(node, (ast.Assign, ast.AnnAssign)):
        targets = node.targets if isinstance(node, ast.Assign) else (node.target,)
        for target in targets:
            for child in ast.walk(target):
                if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Store):
                    yield child.id


def bundle():
    sections = ['# Generated by tools/build.py. Edit src/, not this file.\n']
    owners = {}
    for source in SOURCES:
        text = source.read_text()
        tree = ast.parse(text)
        lines = text.splitlines(keepends=True)
        removed = set()
        for node in tree.body:
            for name in declared_names(node):
                if name in owners and owners[name] != source:
                    raise ValueError(f'Bundle name {name!r} is defined in both {owners[name]} and {source}')
                owners[name] = source
            if isinstance(node, ast.ImportFrom) and node.module in LOCAL_MODULES:
                removed.update(range(node.lineno - 1, node.end_lineno))
        body = ''.join(line for i, line in enumerate(lines) if i not in removed)
        sections.append(f'\n# ---- {source.relative_to(ROOT)} ----\n' + body)
    result = ''.join(sections)
    compile(result, 'scene.py', 'exec')
    return result


if __name__ == '__main__':
    (ROOT / 'scene.py').write_text(bundle())
    print('Built scene.py')
