//! Shared Rust authoring semantics for Manim-compatible `Elbow` geometry.
//!
//! ManimCE defines `Elbow` as one open three-corner VMobject, scaled about the
//! origin to the requested width and then rotates those points about the origin.
//! Noon bakes that constructor rotation into the immutable retained [`VectorPath`]
//! so ordinary snapshot bounds observe the same rotated points. Later authoring
//! transforms still use the shared [`ObjectSnapshot`] transform.

use crate::legacy::{IntoSnapshot, Path};
use noon_core::{Color, ObjectSnapshot, Vec2, VectorPath};

pub const DEFAULT_ELBOW_WIDTH: f32 = 0.2;
pub const DEFAULT_ELBOW_ANGLE: f32 = 0.0;

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ElbowAuthoringError {
    NonFiniteWidth(f32),
    NonFiniteAngle(f32),
}

impl std::fmt::Display for ElbowAuthoringError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NonFiniteWidth(width) => {
                write!(formatter, "elbow width must be finite, got {width}")
            }
            Self::NonFiniteAngle(angle) => {
                write!(formatter, "elbow angle must be finite, got {angle}")
            }
        }
    }
}

impl std::error::Error for ElbowAuthoringError {}

/// ManimCE-compatible open right-angle path.
#[derive(Clone, Debug, PartialEq)]
pub struct Elbow(ObjectSnapshot);

impl Elbow {
    pub fn new() -> Self {
        Self::with_options(DEFAULT_ELBOW_WIDTH, DEFAULT_ELBOW_ANGLE)
            .expect("default Elbow parameters are valid")
    }

    /// Construct the exact v0.21 geometry generated by
    /// `set_points_as_corners([UP, UP + RIGHT, RIGHT])`, followed by
    /// `scale_to_fit_width(width, about_point=ORIGIN)` and rotation about the
    /// origin.
    pub fn with_options(width: f32, angle: f32) -> Result<Self, ElbowAuthoringError> {
        if !width.is_finite() {
            return Err(ElbowAuthoringError::NonFiniteWidth(width));
        }
        if !angle.is_finite() {
            return Err(ElbowAuthoringError::NonFiniteAngle(angle));
        }

        let (sin, cos) = angle.sin_cos();
        let rotate = |point: Vec2| {
            Vec2::new(
                point.x * cos - point.y * sin,
                point.x * sin + point.y * cos,
            )
        };
        let path = VectorPath::new()
            .move_to(rotate(Vec2::new(0.0, width)))
            .line_to(rotate(Vec2::new(width, width)))
            .line_to(rotate(Vec2::new(width, 0.0)));
        Ok(Self(Path::new(path).into_snapshot()))
    }

    pub fn color(mut self, color: Color) -> Self {
        let fill_alpha = self.0.style.fill.map_or(0.0, |fill| fill.alpha);
        let mut fill = color;
        fill.alpha = fill_alpha;
        self.0.style.fill = Some(fill);
        self.0.style.stroke = Some(color);
        self
    }

    pub fn shift(mut self, offset: Vec2) -> Self {
        self.0 = self.0.shift(offset);
        self
    }

    pub fn move_to(mut self, point: Vec2) -> Self {
        self.0 = self.0.move_to(point);
        self
    }

    pub fn scale(mut self, factor: f32) -> Self {
        self.0 = self.0.scale_by(factor);
        self
    }

    pub fn scale_xy(mut self, factor: Vec2) -> Self {
        self.0 = self.0.scale_xy(factor);
        self
    }

    pub fn rotate(mut self, angle: f32) -> Self {
        self.0 = self.0.rotate_by(angle);
        self
    }

    pub fn set_fill(mut self, color: Option<Color>, opacity: Option<f32>) -> Self {
        self.0 = self.0.set_fill(color, opacity);
        self
    }

    pub fn set_stroke(mut self, color: Option<Color>, width: Option<f32>) -> Self {
        self.0 = self.0.set_stroke(color, width);
        self
    }

    pub fn set_opacity(mut self, opacity: f32) -> Self {
        self.0 = self.0.set_opacity(opacity);
        self
    }

    pub fn snapshot(&self) -> &ObjectSnapshot {
        &self.0
    }
}

impl Default for Elbow {
    fn default() -> Self {
        Self::new()
    }
}

impl IntoSnapshot for Elbow {
    fn into_snapshot(self) -> ObjectSnapshot {
        self.0
    }
}

#[cfg(test)]
mod tests {
    use noon_core::{GeometryRef, PathCommand, StrokeCap, StrokeJoin, StrokeWidthMode, WHITE};

    use super::*;

    fn commands(elbow: &Elbow) -> &[PathCommand] {
        match &elbow.snapshot().geometry {
            GeometryRef::VectorPath(path) => path.commands(),
            other => panic!("expected retained VectorPath geometry, got {other:?}"),
        }
    }

    fn assert_close(actual: f32, expected: f32) {
        assert!(
            (actual - expected).abs() <= 1.0e-5,
            "{actual} != {expected}"
        );
    }

    #[test]
    fn default_elbow_matches_manim_open_corner_path_and_style() {
        let elbow = Elbow::new();
        assert_eq!(
            commands(&elbow),
            &[
                PathCommand::MoveTo {
                    to: Vec2::new(0.0, 0.2),
                },
                PathCommand::LineTo {
                    to: Vec2::new(0.2, 0.2),
                },
                PathCommand::LineTo {
                    to: Vec2::new(0.2, 0.0),
                },
            ]
        );
        assert_eq!(elbow.snapshot().transform.rotation, 0.0);
        assert_eq!(elbow.snapshot().style.stroke, Some(WHITE));
        assert_eq!(
            elbow.snapshot().style.fill.map(|color| color.alpha),
            Some(0.0)
        );
        assert_eq!(elbow.snapshot().style.stroke_width, 0.04);
        assert_eq!(
            elbow.snapshot().style.stroke_width_mode,
            StrokeWidthMode::ScreenSpace
        );
        assert_eq!(elbow.snapshot().style.stroke_join, StrokeJoin::Miter);
        assert_eq!(elbow.snapshot().style.stroke_cap, StrokeCap::Butt);
    }

    #[test]
    fn constructor_rotation_is_baked_into_path_for_exact_public_bounds() {
        let angle = 5.0 * std::f32::consts::PI / 4.0;
        let elbow = Elbow::with_options(2.0, angle).unwrap();
        let root_two = 2.0_f32.sqrt();

        assert_eq!(elbow.snapshot().transform.rotation, 0.0);
        assert_close(elbow.snapshot().center().x, 0.0);
        assert_close(elbow.snapshot().center().y, -1.5 * root_two);
        assert_close(elbow.snapshot().width(), 2.0 * root_two);
        assert_close(elbow.snapshot().height(), root_two);
    }

    #[test]
    fn elbow_preserves_manim_zero_and_negative_width_behavior() {
        let zero = Elbow::with_options(0.0, std::f32::consts::FRAC_PI_3).unwrap();
        assert!(commands(&zero).iter().all(|command| match command {
            PathCommand::MoveTo { to } | PathCommand::LineTo { to } => *to == Vec2::ZERO,
            _ => false,
        }));

        let negative = Elbow::with_options(-0.5, -std::f32::consts::FRAC_PI_6).unwrap();
        assert_close(negative.snapshot().center().x, -0.46650636);
        assert_close(negative.snapshot().width(), 0.4330127);
    }

    #[test]
    fn later_rotation_remains_an_ordinary_retained_transform() {
        let elbow = Elbow::with_options(0.2, std::f32::consts::FRAC_PI_4)
            .unwrap()
            .rotate(std::f32::consts::FRAC_PI_2);
        assert_eq!(
            elbow.snapshot().transform.rotation,
            std::f32::consts::FRAC_PI_2
        );
    }

    #[test]
    fn elbow_rejects_non_finite_constructor_inputs() {
        assert!(matches!(
            Elbow::with_options(f32::NAN, 0.0),
            Err(ElbowAuthoringError::NonFiniteWidth(_))
        ));
        assert!(matches!(
            Elbow::with_options(0.2, f32::INFINITY),
            Err(ElbowAuthoringError::NonFiniteAngle(_))
        ));
    }
}
